let UserData = [
  {
      "userName": "조원성",
      "userPhone": "010-4051-3450",
      "userYearStage": "21기",
      "userCoName": "계명대학교",
      "userCoDuty": "매니저",
      "userCoSort": "창업지원단",
      "userCoAddress": "대구 남구 명덕로 104",
      "userCoAddressRest": "동산관 1층 창업지원단",
      "userCoPhone": "010-4051-3450",
      "userCoEmail": "jws3450@kmu.ac.kr",
      "userCoHomePage": "",
      "userCoNotice": "창업지원 사업 담당",
      "userCoImage": "2024-06-01-15-51-52_gon3315.jpeg"
  },
  {
      "userName": "이요한",
      "userPhone": "01095845948",
      "userYearStage": "21기",
      "userCoName": "더좋은사람들",
      "userCoDuty": "대표",
      "userCoSort": "정보통신업",
      "userCoAddress": "대구 달서구 중흥로 3",
      "userCoAddressRest": "달서청년센터 3층 A호",
      "userCoPhone": "01095845948",
      "userCoEmail": "thebetterpeople@naver.com",
      "userCoHomePage": "www.thebetterpeople.co.kr",
      "userCoNotice": "앱/웹 플랫폼 서비스 기획 및 제작 업체입니다.",
      "userCoImage": "2024-06-03-11-09-50_johnleedev_2018.jpg"
  },
  {
      "userName": "배지숙",
      "userPhone": "010-4798-9008 ",
      "userYearStage": "21기",
      "userCoName": "아이나리&대구위수피아 ",
      "userCoDuty": "대표",
      "userCoSort": "수공예상품제조/디자인/행사기획",
      "userCoAddress": "대구 달서구 갈밭로 33",
      "userCoAddressRest": "행복나눔관 2층 청년카페 ",
      "userCoPhone": "070-4238-9008",
      "userCoEmail": "thenobby9@naver.com",
      "userCoHomePage": "www.inari.co.kr",
      "userCoNotice": "세상을 아름답게 디자인하다!\n디자인물, 수공예 답례품\n행사기획, 행사대행 전문\n광관상품 개발을 하고 있습니다.",
      "userCoImage": "2024-06-01-12-58-34_jisukbae.jpeg"
  },
  {
      "userName": "송길수",
      "userPhone": "01066793346",
      "userYearStage": "21기",
      "userCoName": "중소기업지원협동조합",
      "userCoDuty": "대표",
      "userCoSort": "컨설팅",
      "userCoAddress": "대구 서구 와룡로90길 41",
      "userCoAddressRest": "서대구지식산업센터 911호",
      "userCoPhone": "01066793346",
      "userCoEmail": "happysong-gs@hanmail.net",
      "userCoHomePage": "www.smbiz.co.kr",
      "userCoNotice": "종합경영컨설팅그룹인 중소기업지원협동조합의 송길수본부장 입니다.\n저는 창업, 소상공인, 전통시장, 중소기업, 농식품, 유통판로 지원 전문컨설턴트 입니다.",
      "userCoImage": "2024-05-30_songgilsoo.jpg"
  },
  {
      "userName": "이상민",
      "userPhone": "01042633101",
      "userYearStage": "21기",
      "userCoName": "하임로스터리, 구미범산목장",
      "userCoDuty": "대표",
      "userCoSort": "커피교육업체/로스팅업체/카페",
      "userCoAddress": "경북 구미시 인동남길 146",
      "userCoAddressRest": "범산목장",
      "userCoPhone": "0544761113",
      "userCoEmail": "acepcacepc@naver.com",
      "userCoHomePage": "",
      "userCoNotice": "카페창업컨설팅/커피교육/ 카페리컨설팅/원두납품/ 구미범산목장(유기농핸드메이드카페)\n",
      "userCoImage": "2024-05-30-23-46-13_2600334.jpeg"
  },
  {
      "userName": "박진석",
      "userPhone": "01037569752",
      "userYearStage": "21기",
      "userCoName": "N24 PARTNERS",
      "userCoDuty": "대표",
      "userCoSort": "전자상거래 광고/교육/컨설팅",
      "userCoAddress": "대구 북구 칠곡중앙대로 225",
      "userCoAddressRest": "상가 2층",
      "userCoPhone": "07076079752",
      "userCoEmail": "sasha79@naver.com",
      "userCoHomePage": "www.n24partners.com",
      "userCoNotice": "N24 PARTNERS는 국내 기업과 개인이 온라인 시장에서 제대로 성장할 수 있도록 교육과 컨설팅을 진행하며, 급변하는 글로벌 사회에 필요한 가치를 창출하고 있습니다.\n인터넷 쇼핑몰 창업을 지원하는 전문 기업으로, 소상공인 교육과 온라인 마케팅 컨설팅을 함께 제공합니다.\n20년 이상의 쇼핑몰 창업 및 온라인 판로 개척 경험을 가진 이커머스 컨설팅 노하우와 통합 마케팅 역량으로 다양한 파트너사의 성장을 이끌고 있습니다.",
      "userCoImage": "2024-05-31-11-15-08_2600325.jpeg"
  },
  {
      "userName": "이은직",
      "userPhone": "01035145326",
      "userYearStage": "21기",
      "userCoName": "(주)지웍스",
      "userCoDuty": "이사",
      "userCoSort": "서비스/디자인",
      "userCoAddress": "대구 수성구 청수로 101-1",
      "userCoAddressRest": "4층",
      "userCoPhone": "053-216-4126",
      "userCoEmail": "gn-co@daum.net",
      "userCoHomePage": "",
      "userCoNotice": "",
      "userCoImage": null
  },
  {
      "userName": "윤위재",
      "userPhone": "01099232556",
      "userYearStage": "21기",
      "userCoName": "",
      "userCoDuty": "",
      "userCoSort": "",
      "userCoAddress": "",
      "userCoAddressRest": "",
      "userCoPhone": "",
      "userCoEmail": "",
      "userCoHomePage": "",
      "userCoNotice": "",
      "userCoImage": "2024-05-30-20-25-18_ywj150.jpeg"
  },
  {
      "userName": "전기택",
      "userPhone": "010 3813 6517",
      "userYearStage": "21기",
      "userCoName": "팔공생고기 ",
      "userCoDuty": "대표",
      "userCoSort": "한식",
      "userCoAddress": "용산2동 499~10",
      "userCoAddressRest": "",
      "userCoPhone": "",
      "userCoEmail": "",
      "userCoHomePage": "",
      "userCoNotice": "",
      "userCoImage": null
  },
  {
      "userName": "김량희",
      "userPhone": "01042229028",
      "userYearStage": "21기",
      "userCoName": "",
      "userCoDuty": "",
      "userCoSort": "창업, 문화관광 지원업",
      "userCoAddress": "",
      "userCoAddressRest": "",
      "userCoPhone": "",
      "userCoEmail": "",
      "userCoHomePage": "",
      "userCoNotice": "",
      "userCoImage": null
  },
  {
      "userName": "오유진",
      "userPhone": "01057000067",
      "userYearStage": "20기",
      "userCoName": "",
      "userCoDuty": "",
      "userCoSort": "",
      "userCoAddress": "",
      "userCoAddressRest": "",
      "userCoPhone": "",
      "userCoEmail": "",
      "userCoHomePage": "",
      "userCoNotice": "",
      "userCoImage": null
  },
  {
      "userName": "윤효근",
      "userPhone": "01045330407",
      "userYearStage": "20기",
      "userCoName": "문경시도시재생지원센터",
      "userCoDuty": "대표",
      "userCoSort": "비영리",
      "userCoAddress": "",
      "userCoAddressRest": "",
      "userCoPhone": "",
      "userCoEmail": "",
      "userCoHomePage": "",
      "userCoNotice": "",
      "userCoImage": null
  },
  {
      "userName": "홍지아",
      "userPhone": "010-3752-5607",
      "userYearStage": "20기",
      "userCoName": "대경대학교",
      "userCoDuty": "대표",
      "userCoSort": "교육과정개발지원센터",
      "userCoAddress": "경북 경산시 자인면 단북1길 65",
      "userCoAddressRest": "",
      "userCoPhone": "",
      "userCoEmail": "hjahss@tk.ac.kr",
      "userCoHomePage": "https://www.tk.ac.kr/",
      "userCoNotice": "",
      "userCoImage": null
  },
  {
      "userName": "김진주",
      "userPhone": "01056851621",
      "userYearStage": "20기",
      "userCoName": "",
      "userCoDuty": "",
      "userCoSort": "",
      "userCoAddress": "",
      "userCoAddressRest": "",
      "userCoPhone": "",
      "userCoEmail": "",
      "userCoHomePage": "",
      "userCoNotice": "",
      "userCoImage": null
  },
  {
      "userName": "이올가",
      "userPhone": "01085897147",
      "userYearStage": "20기",
      "userCoName": "",
      "userCoDuty": "",
      "userCoSort": "",
      "userCoAddress": "",
      "userCoAddressRest": "",
      "userCoPhone": "",
      "userCoEmail": "",
      "userCoHomePage": "",
      "userCoNotice": "",
      "userCoImage": "2024-06-22-23-18-41_2600308_BeautyPlus_20231104183545919_save.jpg"
  },
  {
      "userName": "이재환",
      "userPhone": "01050492252",
      "userYearStage": "19기",
      "userCoName": "달구벌OA",
      "userCoDuty": "대표",
      "userCoSort": "컴퓨터 및 사무기기,음향,전산소모품,임대",
      "userCoAddress": "대구 중구 태평로 258",
      "userCoAddressRest": "1층",
      "userCoPhone": "",
      "userCoEmail": "ljhwan2252@hanmail.net",
      "userCoHomePage": "",
      "userCoNotice": "",
      "userCoImage": "2024-06-08-10-09-07_ljh2252_1672199523827.jpg"
  },
  {
      "userName": "최현주",
      "userPhone": "01072823352",
      "userYearStage": "19기",
      "userCoName": "제이제이유통",
      "userCoDuty": "대표",
      "userCoSort": "전자상거래 / 도소매 / 작물재배",
      "userCoAddress": "경북 영천시 갈마일길 45",
      "userCoAddressRest": ".",
      "userCoPhone": "010-8258-3391",
      "userCoEmail": "bogyoun3333@naver.com",
      "userCoHomePage": "",
      "userCoNotice": "온라인 판매자에게(셀러) 국내외 과일(농산물)을 위탁공급합니다. 지역의(영천) 농가에서 직수매하여 농가와 상생합니다 농가에서 부족한 포장과 cs 문제를 당사가 대행하며 완벽한 포장으로 고객님께 도착합니다. 즉시 판매가능한 상세페이지 사진자료와 판매가이드, 지역 농산물 일기상황등 정보를 제공해 드리며 1년 내내 판매가능한 농산물을 공급해 드립니다",
      "userCoImage": "2024-06-01-15-52-50_hotcoool.jpeg"
  },
  {
      "userName": "김기만",
      "userPhone": "010-5858-3511",
      "userYearStage": "19기",
      "userCoName": "주식회사 더젠",
      "userCoDuty": "과장",
      "userCoSort": "건설업/실내인테리어시공/정보통신공사업/교육서비스업",
      "userCoAddress": "대구 달서구 월배로 316",
      "userCoAddressRest": "3층, (월촌빌딩)",
      "userCoPhone": "053-716-8580",
      "userCoEmail": "tg@thegen.kr",
      "userCoHomePage": "https://thegen.kr",
      "userCoNotice": "(예비)사회적기업, 실내인테리어공사 및 서비스(도배,타일), 정보통신공사 및 서비스(CCTV, 네트워크)업체 입니다.",
      "userCoImage": "2024-06-01-20-38-35_sph1986x.jpeg"
  },
  {
      "userName": "김재흥",
      "userPhone": "01024798719",
      "userYearStage": "19기",
      "userCoName": "할랄코리아",
      "userCoDuty": "대표",
      "userCoSort": "할랄인증 컨설팅, 수출입",
      "userCoAddress": "대구 달서구 송현로8안길 43",
      "userCoAddressRest": "프라임빌303",
      "userCoPhone": "010-8676-5469",
      "userCoEmail": "halalkim@naver.com",
      "userCoHomePage": "www.halalkorea.org",
      "userCoNotice": "한국의 우수 제품을 할랄인증하여주어 해당 무슬림 국가 시장에 수출",
      "userCoImage": "2024-06-01-15-44-52_halalkim.jpeg"
  },
  {
      "userName": "남광호",
      "userPhone": "01038175824",
      "userYearStage": "19기",
      "userCoName": "신선한 생각 연구소",
      "userCoDuty": "대표",
      "userCoSort": "경영 컨설팅",
      "userCoAddress": "41422",
      "userCoAddressRest": "대구 북구 동암로12길 15",
      "userCoPhone": "010 3817 5824",
      "userCoEmail": "hellofish8282@naver.com",
      "userCoHomePage": "",
      "userCoNotice": "식품 유통 전문 컨설팅 업체 입니다.",
      "userCoImage": null
  },
  {
      "userName": "김상희",
      "userPhone": "010-8812-1256",
      "userYearStage": "19기",
      "userCoName": "미레아우드",
      "userCoDuty": "대표",
      "userCoSort": "제조 원목가구",
      "userCoAddress": "",
      "userCoAddressRest": "",
      "userCoPhone": "",
      "userCoEmail": "",
      "userCoHomePage": "",
      "userCoNotice": "",
      "userCoImage": null
  },
  {
      "userName": "신혜연",
      "userPhone": "010-7598-0300",
      "userYearStage": "19기",
      "userCoName": "더호메디자인연구소(THE HOME DESIGNLAB)",
      "userCoDuty": "대표",
      "userCoSort": "디자인,제조/텍스타일,침구,패브릭소품",
      "userCoAddress": "대구 남구 명덕로 104",
      "userCoAddressRest": "전문관별관102호",
      "userCoPhone": "",
      "userCoEmail": "",
      "userCoHomePage": "",
      "userCoNotice": "",
      "userCoImage": null
  },
  {
      "userName": "이한결",
      "userPhone": "01023536400",
      "userYearStage": "19기",
      "userCoName": "이한결영어수학학원",
      "userCoDuty": "원장",
      "userCoSort": "서비스업",
      "userCoAddress": "대구 북구 내곡로 71",
      "userCoAddressRest": "동아프라자301호",
      "userCoPhone": "",
      "userCoEmail": "",
      "userCoHomePage": "",
      "userCoNotice": "",
      "userCoImage": null
  },
  {
      "userName": "임수현",
      "userPhone": "01050285048",
      "userYearStage": "18기",
      "userCoName": "(사)벤처기업협회대구경북지회",
      "userCoDuty": "사무국장",
      "userCoSort": "공공관계",
      "userCoAddress": "대구 달서구 성서4차첨단로 122-11",
      "userCoAddressRest": "대구경북지방중소벤처기업청 별관 301호",
      "userCoPhone": "053-721-6910",
      "userCoEmail": "kovadg@daum.net",
      "userCoHomePage": "http://kovadg.or.kr",
      "userCoNotice": "",
      "userCoImage": "2024-06-24-08-59-26_wokon_2022_22.jpg"
  },
  {
      "userName": "안민기",
      "userPhone": "010-5001-7298",
      "userYearStage": "18기",
      "userCoName": "",
      "userCoDuty": "학과조교",
      "userCoSort": "",
      "userCoAddress": "",
      "userCoAddressRest": "",
      "userCoPhone": "",
      "userCoEmail": "",
      "userCoHomePage": "",
      "userCoNotice": "",
      "userCoImage": "2024-06-01-15-26-01_minkee333.jpeg"
  },
  {
      "userName": "이정환",
      "userPhone": "01086704590",
      "userYearStage": "18기",
      "userCoName": "",
      "userCoDuty": "",
      "userCoSort": "",
      "userCoAddress": "",
      "userCoAddressRest": "",
      "userCoPhone": "",
      "userCoEmail": "",
      "userCoHomePage": "",
      "userCoNotice": "",
      "userCoImage": null
  },
  {
      "userName": "홍서운",
      "userPhone": "01054394695",
      "userYearStage": "18기",
      "userCoName": "세무법인 울타리",
      "userCoDuty": "",
      "userCoSort": "서비스/세무사",
      "userCoAddress": "대구 수성구 지범로 59",
      "userCoAddressRest": "동아스포츠센터 5층",
      "userCoPhone": "",
      "userCoEmail": "",
      "userCoHomePage": "",
      "userCoNotice": "",
      "userCoImage": null
  },
  {
      "userName": "정성진",
      "userPhone": "01089657817",
      "userYearStage": "17기",
      "userCoName": "",
      "userCoDuty": "",
      "userCoSort": "",
      "userCoAddress": "",
      "userCoAddressRest": "",
      "userCoPhone": "",
      "userCoEmail": "",
      "userCoHomePage": "",
      "userCoNotice": "",
      "userCoImage": null
  },
  {
      "userName": "배정현",
      "userPhone": "01071142054",
      "userYearStage": "13기",
      "userCoName": "",
      "userCoDuty": "",
      "userCoSort": "",
      "userCoAddress": "",
      "userCoAddressRest": "",
      "userCoPhone": "",
      "userCoEmail": "",
      "userCoHomePage": "",
      "userCoNotice": "",
      "userCoImage": null
  },
  {
      "userName": "박창기 ",
      "userPhone": "01038222602",
      "userYearStage": "7기",
      "userCoName": "(주)바른경영연구원 ",
      "userCoDuty": "대표",
      "userCoSort": "서비스/경영컨설팅 ",
      "userCoAddress": "대구 북구 유통단지로 16",
      "userCoAddressRest": "9동8호 ",
      "userCoPhone": "053 384 8501",
      "userCoEmail": "cgp6519@naver.com ",
      "userCoHomePage": "",
      "userCoNotice": "중소기업상담회사로서 기업활동에 필요한\n경영전략수립,인증,사업타당성, 컨설팅,교육등의 업무를 수행하고 있습니다",
      "userCoImage": null
  }
]


export default UserData